/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';
import { ApplicantEvaluationSummary } from './applicantEvaluationSummary';
import { SmokerStatus } from './smokerStatus';


export interface ApplicantResponse { 
    age: number;
    sex: Sex;
    bmi: number;
    children: number;
    smoker: SmokerStatus;
    id: number;
    created_at: string;
    updated_at: string;
    evaluation?: ApplicantEvaluationSummary | null;
}
export namespace ApplicantResponse {
}


