/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicantEvaluationSummary } from './applicantEvaluationSummary';
import { ApplicantResponse } from './applicantResponse';


export interface ApplicantCreateResponse { 
    applicant: ApplicantResponse;
    evaluation: ApplicantEvaluationSummary;
}

