/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';
import { SmokerStatus } from './smokerStatus';


export interface ApplicantUpdate { 
    age: number;
    sex: Sex;
    bmi: number;
    children: number;
    smoker: SmokerStatus;
}
export namespace ApplicantUpdate {
}


