/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelAvailabilityResponse { 
    artifact_exists: boolean;
    artifact_loadable: boolean;
    active_model_version?: string | null;
    active_model_path?: string | null;
}

