/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RiskCategory } from './riskCategory';


export interface ModelMetadataResponse { 
    model_name: string;
    model_version: string;
    labels: Array<RiskCategory>;
    features: Array<string>;
    updated_at: string;
}

