/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RiskCategory = {
    Low: 'Low',
    Medium: 'Medium',
    High: 'High'
} as const;
export type RiskCategory = typeof RiskCategory[keyof typeof RiskCategory];

