/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RiskCategory } from './riskCategory';


export interface RiskEvaluationResponse { 
    evaluation_id: string;
    risk_category: RiskCategory;
    model_version: string;
    created_at: string;
}
export namespace RiskEvaluationResponse {
}


