/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SmokerStatus = {
    Yes: 'yes',
    No: 'no'
} as const;
export type SmokerStatus = typeof SmokerStatus[keyof typeof SmokerStatus];

