/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatisticsRiskCount } from './statisticsRiskCount';


export interface StatisticsSummaryResponse { 
    total_records: number;
    avg_age: number;
    avg_bmi: number;
    avg_charges: number;
    risk_distribution: Array<StatisticsRiskCount>;
}

