/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrainingStatusResponse { 
    run_id?: string | null;
    status: string;
    epochs?: number | null;
    model_version?: string | null;
    started_at?: string | null;
    finished_at?: string | null;
    last_error?: string | null;
    classification_report?: string | null;
}

