/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RiskCategory } from './riskCategory';


export interface TrainingDatasetRow { 
    age?: number | null;
    sex: string;
    bmi?: number | null;
    children?: number | null;
    smoker: string;
    charges_original?: number | null;
    risk_category: RiskCategory;
}
export namespace TrainingDatasetRow {
}


