/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrainingRunResponse { 
    run_id: string;
    status: TrainingRunResponse.StatusEnum;
    epochs: number;
    model_version: string;
    started_at: string;
    finished_at: string;
    classification_report: string;
}
export namespace TrainingRunResponse {
    export const StatusEnum = {
        Completed: 'completed'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


