/**
 * Health Insurance Risk Classifier API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainingDatasetRow } from './trainingDatasetRow';


export interface TrainingDatasetListResponse { 
    items: Array<TrainingDatasetRow>;
    limit: number;
    offset: number;
    total: number;
    has_more: boolean;
}

